### ISSUE TITLE
He atascado con los tests (Tema - Formularios)

### ISSUE THREAD

**Issue by ekavost** [ekavost/practica_dwec_gestor_presupuesto#1]
Hola @pedroprieto,
Parece que todo funciona como se espera, pero, a lo mejor, no es así ya que las dos primeras pruebas (del test6) no las paso. Puedes echar un vistazo?

Un saludo

https://github.com/user-attachments/assets/99daddfd-9e8b-4d9f-a1de-7122ad3e1fbb

**Comment by pedroprieto** [comment]
Buenas,

El problema es este:
https://github.com/ekavost/practica_dwec_gestor_presupuesto/blob/35a4599c33f448764a8ad249d8844d6de2948c42/js/gestionPresupuestoWeb.js#L168

Al utilizar `after`, insertas el formulario a continuación del elemento, no dentro de él. Utiliza `append` en su lugar.

Un saludo!

**Comment by ekavost** [comment]
Claro. El formulario debe aparecer dentro del `div controlesprincipales`: 
 `cy.get("#controlesprincipales form").should("exist");` 
Qué tontería.
Muchas gracias!
